version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - /.*yeoman.*/

skip_branch_with_pr: true

image: Visual Studio 2017

environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le  

cache: '%LOCALAPPDATA%\Yarn'

build_script:

  - dotnet sonarscanner begin /k:"AngularBasic" /d:sonar.organization="gregtrevellick-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:my_encrypted_sonarqube_token" 

  - ps: '
    Set-Location "AngularBasic"

    dotnet restore AngularBasic.csproj

    yarn

    dotnet publish AngularBasic.csproj --configuration "Release" --output "publish"'
    
after_build:

    - dotnet sonarscanner end /d:sonar.login="$env:my_encrypted_sonarqube_token"