version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - /.*yeoman.*/
skip_branch_with_pr: true
image: Visual Studio 2017
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "sonarscanner-msbuild-net46" -y
cache: '%LOCALAPPDATA%\Yarn'
before_build:
    - cmd: nuget restore AngularBasic.sln
    - choco install opencover.portable
    - choco install codecov
    - SonarScanner.MSBuild.exe begin /k:"AngularBasic" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
build:
    project: AngularBasic.sln
    verbosity: minimal
build_script:
- ps: >-
    Set-Location "AngularBasic"

    dotnet restore AngularBasic.csproj

    yarn

    dotnet publish AngularBasic.csproj --configuration "Release" --output "publish"
test: off
after_build:
    - SonarScanner.MSBuild.exe end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
